<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;
class PostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $defaultpwd = '12345678';
        $createMultipleUsers = [
            ['name'=>'MOHD IDHAM BIN ANUR', 'email'=>'idhamanur@gmail.com', 'password'=>bcrypt($defaultpwd), 'role'=>1, 'no_kp'=>'000729120809', 'telefon'=>'0187673729', 'gred'=>'DH52', 'bidang'=>'PERKOMPUTERAN', 'polikk'=>'POLITEKNIK SULTAN SALAHUDDIN ABDUL AZIZ SHAH', 'negeri'=>'SELANGOR', 'tahun_lantikan'=>'2021', 'program'=>'KEJURUTERAAN PERISIAN'],
            ['name'=>'FATIHA AMINUDDIN BINTI ALI', 'email'=>'fatihaaminuddin@gmail.com', 'password'=>bcrypt($defaultpwd), 'role'=>3, 'no_kp'=>'990220019191', 'telefon'=>'01762632681', 'gred'=>'DH44', 'bidang'=>'PERKOMPUTERAN', 'polikk'=>'POLITEKNIK IBRAHIM SULTAN', 'negeri'=>'SELANGOR', 'tahun_lantikan'=>'2021', 'program'=>'KEJURUTERAAN PERISIAN'],
            ['name'=>'SALHANA BINTI SAHIDIN@SALEHUDIN', 'email'=>'salhana@psa.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH52', 'bidang'=>'KEJURUTERAAN MEKANIKAL', 'polikk'=>'POLITEKNIK SULTAN SALAHUDDIN ABDUL AZIZ SHAH', 'negeri'=>'SELANGOR', 'tahun_lantikan'=>'2021', 'program'=>'KEJURUTERAAN MEKANIKAL'],
            ['name'=>'DR. DULINA BINTI THOLIBON', 'email'=>'dulina@ptsn.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH52', 'bidang'=>'KEJURUTERAAN MEKANIKAL', 'polikk'=>'POLITEKNIK TUN SYED NASIR SYED ISMAIL', 'negeri'=>'JOHOR', 'tahun_lantikan'=>'2021', 'program'=>'KEJURUTERAAN MEKANIKAL'],
            ['name'=>'SHAIPUL ANUAR BIN MOHAMED ZAINUDIN', 'email'=>'shaipul@psas.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH52', 'bidang'=>'KEJURUTERAAN MEKANIKAL', 'polikk'=>'POLITEKNIK SULTAN AZLAN SHAH', 'negeri'=>'PERAK', 'tahun_lantikan'=>'2021', 'program'=>'KEJURUTERAAN MEKANIKAL'],
            ['name'=>'NASRUL HAKIME BIN HASSAN', 'email'=>'nasrul@kkss.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH40', 'bidang'=>'KEJURUTERAAN MEKANIKAL', 'polikk'=>'KOLEJ KOMUNITI SUNGAI SIPUT', 'negeri'=>'PERAK', 'tahun_lantikan'=>'2021', 'program'=>'AUTOMOTIF (SERVIS KENDERAAN RINGAN)'],
            ['name'=>'JUMRIANI BINTI NONGKANG', 'email'=>'jumriani@polikk.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH52', 'bidang'=>'KEJURUTERAAN ELEKTRIK', 'polikk'=>'POLITEKNIK KOTA KINABALU SABAH', 'negeri'=>'SABAH', 'tahun_lantikan'=>'2021', 'program'=>'KEJURUTERAAN ELEKTRIK'],
            ['name'=>'NOR \'AZIAH HJ ABDULLAH', 'email'=>'noraziah@pkb.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH52', 'bidang'=>'KEJURUTERAAN ELEKTRIK', 'polikk'=>'POLITEKNIK KOTA BHARU', 'negeri'=>'KELANTAN', 'tahun_lantikan'=>'2021', 'program'=>'KEJURUTERAAN ELEKTRIK'],
            ['name'=>'MD EMRAN BIN SAIDI', 'email'=>'emran.kkbbm@celt.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH48', 'bidang'=>'KEJURUTERAAN ELEKTRIK', 'polikk'=>'KOLEJ KOMUNITI BUKIT BERUANG', 'negeri'=>'MELAKA', 'tahun_lantikan'=>'2021', 'program'=>'TEKNOLOGI ELEKTRIK'],
            ['name'=>'KHAIRULFADILAH BINTI MOHAMAD SAZALI', 'email'=>'kfadilah@poliku.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH44', 'bidang'=>'KEJURUTERAAN ELEKTRIK', 'polikk'=>'POLITEKNIK KUCHING SARAWAK', 'negeri'=>'SARAWAK', 'tahun_lantikan'=>'2021', 'program'=>'KEJURUTERAAN ELEKTRIK'],
            ['name'=>'NOORFOZILA BINTI BAHARI', 'email'=>'noorfozila@polisas.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH54', 'bidang'=>'KEJURUTERAAN ELEKTRIK', 'polikk'=>'POLITEKNIK SULTAN HAJI AHMAD SHAH', 'negeri'=>'PAHANG', 'tahun_lantikan'=>'2021', 'program'=>'KEJURUTERAAN ELEKTRIK'],
            ['name'=>'FAIZAH BINTI AMIR', 'email'=>'faizah@polisas.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH52', 'bidang'=>'KEJURUTERAAN ELEKTRIK', 'polikk'=>'POLITEKNIK SULTAN HAJI AHMAD SHAH', 'negeri'=>'PAHANG', 'tahun_lantikan'=>'2021', 'program'=>'KEJURUTERAAN ELEKTRIK'],
            ['name'=>'SULIE AK SLAT', 'email'=>'sulie@polikk.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH52', 'bidang'=>'KEJURUTERAAN AWAM & ALAM BINA', 'polikk'=>'POLITEKNIK KOTA KINABALU SABAH', 'negeri'=>'SABAH', 'tahun_lantikan'=>'2021', 'program'=>'KEJURUTERAAN AWAM'],
            ['name'=>'ZURAIDAH BINTI HASHIM', 'email'=>'zuraidahhashim@staff.polisas.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH52', 'bidang'=>'KEJURUTERAAN AWAM & ALAM BINA', 'polikk'=>'POLITEKNIK SULTAN HAJI AHMAD SHAH', 'negeri'=>'PAHANG', 'tahun_lantikan'=>'2021', 'program'=>'KEJURUTERAAN AWAM'],
            ['name'=>'ZARINAH BINTI ZAINI', 'email'=>'zzarinah@psa.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH52', 'bidang'=>'KEJURUTERAAN AWAM & ALAM BINA', 'polikk'=>'POLITEKNIK SULTAN SALAHUDDIN ABDUL AZIZ SHAH', 'negeri'=>'SELANGOR', 'tahun_lantikan'=>'2021', 'program'=>'KEJURUTERAAN AWAM'],
            ['name'=>'NOR HAYATI BINTI AB. RAHIM', 'email'=>'hayati@psmza.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH48', 'bidang'=>'KEJURUTERAAN AWAM & ALAM BINA', 'polikk'=>'POLITEKNIK SULTAN MIZAN ZAINAL ABIDIN', 'negeri'=>'TERENGGANU', 'tahun_lantikan'=>'2021', 'program'=>'KEJURUTERAAN AWAM'],
            ['name'=>'ROHAZA BINTI MAJID', 'email'=>'rohaza@psa.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH48', 'bidang'=>'KEJURUTERAAN AWAM & ALAM BINA', 'polikk'=>'POLITEKNIK SULTAN SALAHUDDIN ABDUL AZIZ SHAH', 'negeri'=>'SELANGOR', 'tahun_lantikan'=>'2021', 'program'=>'KEJURUTERAAN AWAM'],
            ['name'=>'FATIMAHWATI BT ABDUL HAMID', 'email'=>'fatimahwati@polinilai.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH52', 'bidang'=>'KEJURUTERAAN AWAM & ALAM BINA', 'polikk'=>'POLITEKNIK NILAI', 'negeri'=>'NEGERI SEMBILAN', 'tahun_lantikan'=>'2021', 'program'=>'SENIBINA LANDSKAP'],
            ['name'=>'AZHAR BIN YAAKUB', 'email'=>'azhar@kkmasjidtanah.onmicrosoft.com', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH52', 'bidang'=>'KEJURUTERAAN AWAM & ALAM BINA', 'polikk'=>'KOLEJ KOMUNITI MASJID TANAH', 'negeri'=>'MELAKA', 'tahun_lantikan'=>'2021', 'program'=>'SENIBINA LANDSKAP'],
            ['name'=>'MOHAMAD IMRAN BIN HASSAN', 'email'=>'imran@kkmasjidtanah.onmicrosoft.com', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH48', 'bidang'=>'KEJURUTERAAN AWAM & ALAM BINA', 'polikk'=>'KOLEJ KOMUNITI MASJID TANAH', 'negeri'=>'MELAKA', 'tahun_lantikan'=>'2021', 'program'=>'SENIBINA LANDSKAP'],
            ['name'=>'MOHD AZRAN BIN MOHD SALLEH', 'email'=>'azran@kkselandar.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH48', 'bidang'=>'PERKOMPUTERAN', 'polikk'=>'KOLEJ KOMUNITI SELANDAR', 'negeri'=>'MELAKA', 'tahun_lantikan'=>'2021', 'program'=>'SISTEM KOMPUTER DAN RANGKAIAN'],
            ['name'=>'HAMIDAH BINTI MOHAMED SHAH', 'email'=>'hamidah@kkmasjidtanah.onmicrosoft.com', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH48', 'bidang'=>'PERKOMPUTERAN', 'polikk'=>'KOLEJ KOMUNITI MASJID TANAH', 'negeri'=>'MELAKA', 'tahun_lantikan'=>'2021', 'program'=>'TEKNOLOGI MAKLUMAT'],
            ['name'=>'NORSHAHADAH BINTI ABD RAHMAN', 'email'=>'norshahadah@pss.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH44', 'bidang'=>'PERKOMPUTERAN', 'polikk'=>'POLITEKNIK SANDAKAN SABAH', 'negeri'=>'SABAH', 'tahun_lantikan'=>'2021', 'program'=>'TEKNOLOGI MAKLUMAT'],
            ['name'=>'SUDIMAN BIN SUHAILI', 'email'=>'sudiman@pmu.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH48', 'bidang'=>'PERKOMPUTERAN', 'polikk'=>'POLITEKNIK MUKAH', 'negeri'=>'SARAWAK', 'tahun_lantikan'=>'2021', 'program'=>'TEKNOLOGI MAKLUMAT'],
            ['name'=>'ULAIMI YAHYA', 'email'=>'ulaimi@pjk.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH52', 'bidang'=>'PENGURUSAN & PERDAGANGAN', 'polikk'=>'POLITEKNIK JELI', 'negeri'=>'KELANTAN', 'tahun_lantikan'=>'2021', 'program'=>'PERDAGANGAN'],
            ['name'=>'SALEHAN BIN MARSIM', 'email'=>'salehan@psas.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH52', 'bidang'=>'PENGURUSAN & PERDAGANGAN', 'polikk'=>'POLITEKNIK SULTAN AZLAN SHAH', 'negeri'=>'PERAK', 'tahun_lantikan'=>'2021', 'program'=>'PERDAGANGAN'],
            ['name'=>'ATI ARINI BT SALIM', 'email'=>'atiarini@polipd.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH52', 'bidang'=>'PENGURUSAN & PERDAGANGAN', 'polikk'=>'POLITEKNIK PORT DICKSON', 'negeri'=>'NEGERI SEMBILAN', 'tahun_lantikan'=>'2021', 'program'=>'PERAKAUNAN'],
            ['name'=>'YUFIZA BINTI MOHD YUSOF', 'email'=>'yufiza@puo.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'BERSARA', 'bidang'=>'PENGURUSAN & PERDAGANGAN', 'polikk'=>'TELAH BERSARA', 'negeri'=>'PERAK', 'tahun_lantikan'=>'2021', 'program'=>'PERAKAUNAN'],
            ['name'=>'HASNIDA BINTI ISMAIL', 'email'=>'hasnida_ismail@pms.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH52', 'bidang'=>'PENGURUSAN & PERDAGANGAN', 'polikk'=>'POLITEKNIK MUADZAM SHAH', 'negeri'=>'PAHANG', 'tahun_lantikan'=>'2021', 'program'=>'STATISTIK / BUSINESS'],
            ['name'=>'SUZILA BINTI ABDUL LATIFF', 'email'=>'suzila@lecturer.kklej.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH44', 'bidang'=>'PENGURUSAN & PERDAGANGAN', 'polikk'=>'KOLEJ KOMUNITI LEDANG', 'negeri'=>'JOHOR', 'tahun_lantikan'=>'2021', 'program'=>'ETIKA PERNIAGAAN'],
            ['name'=>'AHMAD RASA\'ARIM BIN RAZZALI', 'email'=>'ahmad.rasaarim@pmku.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH52', 'bidang'=>'HOSPITALITI & PELANCONGAN', 'polikk'=>'POLITEKNIK METrO KUANTAN', 'negeri'=>'PAHANG', 'tahun_lantikan'=>'2021', 'program'=>'HOSPITALITI (PERKHIDMATAN MAKANAN)'],
            ['name'=>'ZAKINA IZIENTY BINTI ZAINAL', 'email'=>'zakina@kkss.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH48', 'bidang'=>'HOSPITALITI & PELANCONGAN', 'polikk'=>'CUTI BELAJAR', 'negeri'=>'PERAK', 'tahun_lantikan'=>'2021', 'program'=>'PENGEMBARAAN PELANCONGAN'],
            ['name'=>'KHAIRUL ASHIKHIN BT ABDULLAH SUHAMI', 'email'=>'ashikhin@kkchenderoh.onmicrosoft.com', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH52', 'bidang'=>'PENGAJIAN PERKHIDMATAN', 'polikk'=>'KOLEJ KOMUNITI CHENDEROH', 'negeri'=>'PERAK', 'tahun_lantikan'=>'2021', 'program'=>'KULINARI'],
            ['name'=>'ZAFEERA BINTI ZULKEFLI', 'email'=>'zafeera.zulkefli.kk@1govuc.gov.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH42', 'bidang'=>'PENGAJIAN PERKHIDMATAN', 'polikk'=>'KOLEJ KOMUNITI KOTA MELAKA', 'negeri'=>'MELAKA', 'tahun_lantikan'=>'2021', 'program'=>'KULINARI'],
            ['name'=>'INTANKU SALWA BT SHAMSUDDIN', 'email'=>'intankusalwa@staff.pmm.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH48', 'bidang'=>'PENGAJIAN UMUM', 'polikk'=>'POLITEKNIK MERLIMAU MELAKA', 'negeri'=>'MELAKA', 'tahun_lantikan'=>'2021', 'program'=>'PENDIDIKAN MATEMATIK'],
            ['name'=>'LIM BOON PING', 'email'=>'limbp@pbu.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH48', 'bidang'=>'PENGAJIAN UMUM', 'polikk'=>'POLITEKNIK BALIK PULAU', 'negeri'=>'PULAU PINANG', 'tahun_lantikan'=>'2021', 'program'=>'MATEMATIK / IT'],
            ['name'=>'KHAIRUL ANUAR BIN KAMAR', 'email'=>'khairul_anuar@kkpbe.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH52', 'bidang'=>'PENGAJIAN UMUM', 'polikk'=>'KOLEJ KOMUNITI PAYA BESAR', 'negeri'=>'PAHANG', 'tahun_lantikan'=>'2021', 'program'=>'PENDIDIKAN ISLAM'],
            ['name'=>'AINA FATHIAH BINTI ZUHAIDI', 'email'=>'a.fathiah@ptsn.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'870202115316', 'telefon'=>'0133665645', 'gred'=>'DH48', 'bidang'=>'TEKNOLOGI PERTANIAN', 'polikk'=>'POLITEKNIK TUN SYED NASIR SYED ISMAIL', 'negeri'=>'JOHOR', 'tahun_lantikan'=>'2022', 'program'=>'TEKNOLOGI KIMIA (LEMAK & MINYAK)'],
            ['name'=>'AINUL AZNIZA BINTI AHMAD ZAINI', 'email'=>'ainul@pmm.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'760124025042', 'telefon'=>'0192649842', 'gred'=>'DH48', 'bidang'=>'KEJURUTERAAN MEKANIKAL', 'polikk'=>'POLITEKNIK MERLIMAU MELAKA ', 'negeri'=>'MELAKA', 'tahun_lantikan'=>'2022', 'program'=>'KEJURUTERAAN MEKATRONIK'],
            ['name'=>'AINUL HUSNA BINTI ABDUL HALIM', 'email'=>'ainul@kkbaganserai.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'881214025434', 'telefon'=>'0174669836', 'gred'=>'DH44', 'bidang'=>'TEKNOLOGI PERTANIAN', 'polikk'=>'KOLEJ KOMUNITI BAGAN SERAI', 'negeri'=>'PULAU PINANG', 'tahun_lantikan'=>'2022', 'program'=>'PEMPROSESAN DAN KAWALAN MUTU MAKANAN'],
            ['name'=>'AZLILAWATI BINTI ABU BAKAR', 'email'=>'azlilawati@pmm.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'720711015598', 'telefon'=>'0196697051', 'gred'=>'DH48', 'bidang'=>'KEJURUTERAAN ELEKTRIK', 'polikk'=>'POLITEKNIK MERLIMAU MELAKA ', 'negeri'=>'MELAKA', 'tahun_lantikan'=>'2022', 'program'=>'KEJURUTERAAN ELEKTRONIK (KOMUNIKASI)'],
            ['name'=>'AZLINA BINTI ABDUL AZIZ', 'email'=>'azlina@pmu.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'810514085764', 'telefon'=>'Belum kemaskini', 'gred'=>'DH48', 'bidang'=>'KEJURUTERAAN ELEKTRIK', 'polikk'=>'POLITEKNIK MUKAH SARAWAK ', 'negeri'=>'SARAWAK', 'tahun_lantikan'=>'2022', 'program'=>'KEJURUTERAAN ELEKTRONIK (KOMUNIKASI)'],
            ['name'=>'CHE AZLINA BINTI CHE NOROHOSENI', 'email'=>'cheazlina@polipd.edy.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'810711095056', 'telefon'=>'0124632620', 'gred'=>'DH48', 'bidang'=>'KEJURUTERAAN MEKANIKAL', 'polikk'=>'POLITEKNIK PORT DICKSON ', 'negeri'=>'NEGERI SEMBILAN', 'tahun_lantikan'=>'2022', 'program'=>'KEJURUTERAAN MEKANIKAL'],
            ['name'=>'CHE KU FARHANA BINTI CHE KU ALAM', 'email'=>'farhana@kkktu.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'820204115218', 'telefon'=>'0125238489', 'gred'=>'DH44', 'bidang'=>'KEJURUTERAAN ELEKTRIK', 'polikk'=>'KOLEJ KOMUNITI KUALA TERENGGANU', 'negeri'=>'TERENGGANU', 'tahun_lantikan'=>'2022', 'program'=>'TEKNOLOGI ELEKTRIK'],
            ['name'=>'CR. DR. LING YING LEH', 'email'=>'jossted@poliku.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'740831135285', 'telefon'=>'0163982588', 'gred'=>'DH52', 'bidang'=>'PENGAJIAN UMUM', 'polikk'=>'POLITEKNIK KUCHING SARAWAK ', 'negeri'=>'SARAWAK', 'tahun_lantikan'=>'2022', 'program'=>'MATEMATIK, SAINS DAN KOMPUTER'],
            ['name'=>'DR. MUHAMMAD NAZRI BIN ABDUL HALIM', 'email'=>'nazrifaiz@yahoo.com', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH52', 'bidang'=>'PENGURUSAN & PERDAGANGAN', 'polikk'=>'POLITEKNIK METrO JOHOR BAHRU ', 'negeri'=>'JOHOR', 'tahun_lantikan'=>'2022', 'program'=>'DLS, DIB, DEN, DPM '],
            ['name'=>'ENI BINTI AZNAN', 'email'=>'enikkbk16@gmail.com', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'801026025928', 'telefon'=>'0126676476', 'gred'=>'DH44', 'bidang'=>'REKA BENTUK & KREATIF', 'polikk'=>'KOLEJ KOMUNITI BUKIT MERTAJAM', 'negeri'=>'PULAU PINANG', 'tahun_lantikan'=>'2022', 'program'=>'FESYEN & PAKAIAN'],
            ['name'=>'JULIA BINTI JAMALUDDIN', 'email'=>'julia@pkb.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'810122045368', 'telefon'=>'0133387578', 'gred'=>'DH44', 'bidang'=>'KEJURUTERAAN MEKANIKAL', 'polikk'=>'POLITEKNIK KOTA BHARU ', 'negeri'=>'KELANTAN', 'tahun_lantikan'=>'2022', 'program'=>'AGRICULTURE ENGINEERING'],
            ['name'=>'JULIANA BINTI MD JUSOH', 'email'=>'juliana@pkb.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'790409015224', 'telefon'=>'0132373792', 'gred'=>'DH48', 'bidang'=>'KEJURUTERAAN ELEKTRIK', 'polikk'=>'POLITEKNIK KOTA BHARU ', 'negeri'=>'KELANTAN', 'tahun_lantikan'=>'2022', 'program'=>'KEJURUTERAAN ELEKTRIK'],
            ['name'=>'KHIRUN BIN MD SHAH', 'email'=>'khirun@psis.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'790730075733', 'telefon'=>'0193348005', 'gred'=>'DH48', 'bidang'=>'HOSPITALITI & PELANCONGAN', 'polikk'=>'POLITEKNIK SULTAN IDRIS SHAH ', 'negeri'=>'SELANGOR', 'tahun_lantikan'=>'2022', 'program'=>'PENGURUSAN PELANCONGAN'],
            ['name'=>'LAILA BINTI MUSA', 'email'=>'laila@ptss.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'761120025330', 'telefon'=>'0192586555', 'gred'=>'DH52', 'bidang'=>'PENGURUSAN & PERDAGANGAN', 'polikk'=>'POLITEKNIK TUANKU SYED SIRAJUDDIN ', 'negeri'=>'PERLIS', 'tahun_lantikan'=>'2022', 'program'=>'AKAUNTANSI'],
            ['name'=>'LATENAZURAINI BINTI SAARI', 'email'=>'latenazuraini@polipd.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH48', 'bidang'=>'KEJURUTERAAN ELEKTRIK', 'polikk'=>'POLITEKNIK PORT DICKSON', 'negeri'=>'NEGERI SEMBILAN', 'tahun_lantikan'=>'2022', 'program'=>'KEJURUTERAAN ELEKTRIK'],
            ['name'=>'LENNY LAI MEI LAN', 'email'=>'lennylml@kkmas.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'820830135590', 'telefon'=>'0177557163', 'gred'=>'DH48', 'bidang'=>'PERKOMPUTERAN', 'polikk'=>'KOLEJ KOMUNITI MAS GADING', 'negeri'=>'SARAWAK', 'tahun_lantikan'=>'2022', 'program'=>'TEKNOLOGI MAKLUMAT'],
            ['name'=>'TS. MAHALETCHUMY A/P KRISHNAMOORTHY', 'email'=>'maha@kkrembau.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'860710565808', 'telefon'=>'0102059448', 'gred'=>'DH44', 'bidang'=>'TEKNOLOGI PERTANIAN', 'polikk'=>'KOLEJ KOMUNITI REMBAU', 'negeri'=>'NEGERI SEMBILAN', 'tahun_lantikan'=>'2022', 'program'=>'AGROTEKNOLOGI'],
            ['name'=>'MANISAH BINTI ABD HAMID', 'email'=>'manisah@mail.cckk.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'831128086120', 'telefon'=>'0124174001', 'gred'=>'DH44', 'bidang'=>'HOSPITALITI & PELANCONGAN', 'polikk'=>'KOLEJ KOMUNITI KUALA KANGSAR', 'negeri'=>'PERAK', 'tahun_lantikan'=>'2022', 'program'=>'SPT , DPT'],
            ['name'=>'MARZITA BINTI MUHAMAD TAZI', 'email'=>'marzita.tazi@polikk.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'771117146042', 'telefon'=>'0123195642', 'gred'=>'DH52', 'bidang'=>'KEJURUTERAAN ELEKTRIK', 'polikk'=>'BAHAGIAN KURIKULUM, JPPKK', 'negeri'=>'WILAYAH PERSEKUTUAN PUTRAJAYA', 'tahun_lantikan'=>'2022', 'program'=>'KEJURUTERAAN ELEKTRIK'],
            ['name'=>'MOHAMAD ZULHILMY BIN MOHAMAD YUSOP', 'email'=>'zulhilmy@politawau.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'760210145067', 'telefon'=>'0127036308', 'gred'=>'DH48', 'bidang'=>'HOSPITALITI & PELANCONGAN', 'polikk'=>'POLITEKNIK TAWAU ', 'negeri'=>'SABAH', 'tahun_lantikan'=>'2022', 'program'=>'PENGURUSAN PELANCONGAN'],
            ['name'=>'MOHAMMAD AZMIN BIN ZAINAL', 'email'=>'azmin@polibanting.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'870206385049', 'telefon'=>'0199199085', 'gred'=>'DH44', 'bidang'=>'KEJURUTERAAN MEKANIKAL', 'polikk'=>'POLITEKNIK BANTING ', 'negeri'=>'SELANGOR', 'tahun_lantikan'=>'2022', 'program'=>'KEJURUTERAAN PENYENGGARAAN PESAWAT'],
            ['name'=>'MOHAMMAD HAIRY BIN KHARAUDDIN', 'email'=>'mhairydin5857@gmail.com', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'820401015857', 'telefon'=>'0133374812', 'gred'=>'DH48', 'bidang'=>'KEJURUTERAAN ELEKTRIK', 'polikk'=>'KOLEJ KOMUNITI MASJID TANAH', 'negeri'=>'MELAKA', 'tahun_lantikan'=>'2022', 'program'=>'RAIL SIGNALLING & COMMUNICATION TECH.'],
            ['name'=>'MOHD AZIAN BIN HUSIN @ CHE HAMAT', 'email'=>'azian@kkpmas.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH52', 'bidang'=>'PENGURUSAN & PERDAGANGAN', 'polikk'=>'KOLEJ KOMUNITI CAW. RANTAU PANJANG', 'negeri'=>'KELANTAN', 'tahun_lantikan'=>'2022', 'program'=>'PERKHIDMATAN LOGISTIK'],
            ['name'=>'TS. MOHD NAIM BIN AWANG', 'email'=>'mnaim@puo.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'820606025127', 'telefon'=>'Belum kemaskini', 'gred'=>'DH52', 'bidang'=>'KEJURUTERAAN MEKANIKAL', 'polikk'=>'POLITEKNIK BAGAN DATUK ', 'negeri'=>'PERAK', 'tahun_lantikan'=>'2022', 'program'=>'SENIBINA KAPAL '],
            ['name'=>'MOHD SHAHRIR BIN AHMAD ZAINI', 'email'=>'mohdshahrir@pmbs.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'760621085185', 'telefon'=>'0197727323', 'gred'=>'DH48', 'bidang'=>'HOSPITALITI & PELANCONGAN', 'polikk'=>'POLITEKNIK METRO BETONG ', 'negeri'=>'SARAWAK', 'tahun_lantikan'=>'2022', 'program'=>'PENGURUSAN PELANCONGAN (DUP)'],
            ['name'=>'MOHD ZAMRI BIN JAMALUDIN', 'email'=>'zamri_jamaludin@psis.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH44', 'bidang'=>'KEJURUTERAAN AWAM & ALAM BINA', 'polikk'=>'POLITEKNIK SULTAN IDRIS SHAH ', 'negeri'=>'SELANGOR', 'tahun_lantikan'=>'2022', 'program'=>'KEJURUTERAAN ALAM SEKITAR'],
            ['name'=>'MUHAMMAD ISWAN BIN MOHAMAD AYOB', 'email'=>'iswan@polibanting.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'820422016197', 'telefon'=>'0127343802', 'gred'=>'DH48', 'bidang'=>'KEJURUTERAAN MEKANIKAL', 'polikk'=>'POLITEKNIK BANTING SELANGOR ', 'negeri'=>'SELANGOR', 'tahun_lantikan'=>'2022', 'program'=>'PENYENGGARAAN PESAWAT/DAM'],
            ['name'=>'MUHD FADHLULLAH BIN RASHID', 'email'=>'muhd_fadhlullah@psmza.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'821115115149', 'telefon'=>'0122844475', 'gred'=>'DH52', 'bidang'=>'KEJURUTERAAN AWAM & ALAM BINA', 'polikk'=>'POLITEKNIK SULTAN MIZAN ZAINAL ABIDIN ', 'negeri'=>'TERENGGANU', 'tahun_lantikan'=>'2022', 'program'=>'KEJURUTERAAN AWAM'],
            ['name'=>'NGATINAH BINTI JASWADI', 'email'=>'ngatinah@pmm.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH44', 'bidang'=>'PENGAJIAN UMUM', 'polikk'=>'POLITEKNIK MERLIMAU MELAKA ', 'negeri'=>'MELAKA', 'tahun_lantikan'=>'2022', 'program'=>'SAINS DAN MATEMATIK'],
            ['name'=>'NOR ASMA BINTI MAMAT', 'email'=>'nor.asma@pkb.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'821020035402', 'telefon'=>'0199162266', 'gred'=>'DH48', 'bidang'=>'KEJURUTERAAN AWAM & ALAM BINA', 'polikk'=>'POLITEKNIK KOTA BHARU ', 'negeri'=>'KELANTAN', 'tahun_lantikan'=>'2022', 'program'=>'UKUR BAHAN'],
            ['name'=>'NOR AZIMAH BINTI MUSTAFAR', 'email'=>'norazimah.mus@puo.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH44', 'bidang'=>'PENGAJIAN UMUM', 'polikk'=>'POLITEKNIK UNGKU OMAR', 'negeri'=>'PERAK', 'tahun_lantikan'=>'2022', 'program'=>'MATEMATIK, SAINS DAN KOMPUTER'],
            ['name'=>'NORAWATI BINTI MASRO', 'email'=>'masronorawati@gmail.com', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'750113015296', 'telefon'=>'0192339336', 'gred'=>'DH48', 'bidang'=>'KEJURUTERAAN ELEKTRIK', 'polikk'=>'KOLEJ KOMUNITI SABAK BERNAM', 'negeri'=>'SELANGOR', 'tahun_lantikan'=>'2022', 'program'=>'TEKNOLOGI ELEKTRIK'],
            ['name'=>'NORIZZATI BINTI ABD LATIF', 'email'=>'norizzati@pms.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'820528145552', 'telefon'=>'0123644611', 'gred'=>'DH48', 'bidang'=>'REKA BENTUK & KREATIF', 'polikk'=>'POLITEKNIK MUADZAM SHAH ', 'negeri'=>'PAHANG', 'tahun_lantikan'=>'2022', 'program'=>'TEKNOLOGI MEDIA CETAK'],
            ['name'=>'NORLEZA BINTI LEHAT', 'email'=>'norleza@pms.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'751023015748', 'telefon'=>'0126077458', 'gred'=>'DH48', 'bidang'=>'PENGURUSAN & PERDAGANGAN', 'polikk'=>'POLITEKNIK MUADZAM SHAH ', 'negeri'=>'PAHANG', 'tahun_lantikan'=>'2022', 'program'=>'PENGAJIAN PERNIAGAAN, AKAUNTANSI'],
            ['name'=>'RAFIZAH BINTI SHAHARUDDIN', 'email'=>'rafizah@pbu.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH48', 'bidang'=>'PERKOMPUTERAN', 'polikk'=>'POLITEKNIK BALIK PULAU ', 'negeri'=>'PULAU PINANG', 'tahun_lantikan'=>'2022', 'program'=>'TEKNOLOGI MAKLUMAT (TEKNOLOGI DIGITAL)'],
            ['name'=>'RAZZATUL IZA ZURITA BINTI RASALLI', 'email'=>'iza@lecturer.kklej.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'810225145564', 'telefon'=>'0176057054', 'gred'=>'DH48', 'bidang'=>'PENGAJIAN UMUM', 'polikk'=>'KOLEJ KOMUNITI LEDANG', 'negeri'=>'JOHOR', 'tahun_lantikan'=>'2022', 'program'=>'SAINS'],
            ['name'=>'SAPTUAH@SAPTUYAH BT.MARJIRI', 'email'=>'saptuyah@pmbs.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'650925135244', 'telefon'=>'0194100019', 'gred'=>'DH48', 'bidang'=>'PENGURUSAN & PERDAGANGAN', 'polikk'=>'POLITEKNIK METRO BETONG SARAWAK', 'negeri'=>'SARAWAK', 'tahun_lantikan'=>'2022', 'program'=>'PERDAGANGAN'],
            ['name'=>'SARAH NARIMAH NOORAZYZE BINTI ZAINAL RAMLAN', 'email'=>'sarah@polinilai.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'810426016304', 'telefon'=>'0168530506', 'gred'=>'DH48', 'bidang'=>'KEJURUTERAAN MEKANIKAL', 'polikk'=>'POLITEKNIK NILAI ', 'negeri'=>'NEGERI SEMBILAN', 'tahun_lantikan'=>'2022', 'program'=>'KEJURUTERAAN MEKANIKAL'],
            ['name'=>'SITI FADZLINA BINTI MOHAMAD ASRI', 'email'=>'ctfadzlina@psa.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'770105145072', 'telefon'=>'0193329569', 'gred'=>'DH48', 'bidang'=>'PENGAJIAN UMUM', 'polikk'=>'POLITEKNIK SULTAN SALAHUDDIN ABDUL AZIZ SHAH ', 'negeri'=>'SELANGOR', 'tahun_lantikan'=>'2022', 'program'=>'MATEMATIK, SAINS DAN KOMPUTER'],
            ['name'=>'SITI NORSHAFINAZ BINTI MOHD NOH', 'email'=>'nshafinaz@puo.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'810309105244', 'telefon'=>'Belum kemaskini', 'gred'=>'DH48', 'bidang'=>'PENGAJIAN UMUM', 'polikk'=>'POLITEKNIK UNGKU OMAR ', 'negeri'=>'PERAK', 'tahun_lantikan'=>'2022', 'program'=>'MATEMATIK, SAINS DAN KOMPUTER'],
            ['name'=>'SYAKIRAH BINTI MANSOR', 'email'=>'syakirah@tvet.pmj.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'820404016054', 'telefon'=>'0197508482', 'gred'=>'DH48', 'bidang'=>'PERKOMPUTERAN', 'polikk'=>'POLITEKNIK MERSING ', 'negeri'=>'JOHOR', 'tahun_lantikan'=>'2022', 'program'=>'TEKNOLOGI MAKLUMAT (TEKNOLOGI DIGITAL)'],
            ['name'=>'TS. BABBY FRESKAYANI@ IZYANI BINTI KALIWON', 'email'=>'izyani@polikk.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'820116715002', 'telefon'=>'0178961511', 'gred'=>'DH52', 'bidang'=>'KEJURUTERAAN AWAM & ALAM BINA', 'polikk'=>'POLITEKNIK KOTA KINABALU', 'negeri'=>'SABAH', 'tahun_lantikan'=>'2022', 'program'=>'KEJURUTERAAN AWAM'],
            ['name'=>'TS. DR. SHARIFAH NADIYAH BINTI RAZALI', 'email'=>'sharifahnadiyah@staf.kkselandar.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH48', 'bidang'=>'PERKOMPUTERAN', 'polikk'=>'KOLEJ KOMUNITI SELANDAR', 'negeri'=>'MELAKA', 'tahun_lantikan'=>'2022', 'program'=>'KOMPUTER DAN RANGKAIAN'],
            ['name'=>'TS. JALIFA BINTI RIDZUAN', 'email'=>'jalifa@live.com', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'840801126124', 'telefon'=>'0173767267', 'gred'=>'DH48', 'bidang'=>'TEKNOLOGI PERTANIAN', 'polikk'=>'KOLEJ KOMUNITI JELEBU', 'negeri'=>'NEGERI SEMBILAN', 'tahun_lantikan'=>'2022', 'program'=>'PEMPROSESAN DAN KAWALAN MUTU MAKANAN'],
            ['name'=>'TS. KASLIA BINTI KASIRAN', 'email'=>'kaslia@kkkla.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'790409015224', 'telefon'=>'0132373792', 'gred'=>'DH48', 'bidang'=>'KEJURUTERAAN ELEKTRIK', 'polikk'=>'KOLEJ KOMUNITI KUALA LANGAT', 'negeri'=>'SELANGOR', 'tahun_lantikan'=>'2022', 'program'=>'TEKNOLOGI ELEKTRIK'],
            ['name'=>'TS. KASWATI BINTI SALLEH', 'email'=>'kaswatisalleh@gmail.com', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH48', 'bidang'=>'PERKOMPUTERAN', 'polikk'=>'KOLEJ KOMUNITI KUALA LANGAT', 'negeri'=>'SELANGOR', 'tahun_lantikan'=>'2022', 'program'=>'TEKNOLOGI MAKLUMAT'],
            ['name'=>'Ts. MOHANADHAS KANAGARAJ', 'email'=>'stbmohan@gmail.com', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'760315025811', 'telefon'=>'0194566184', 'gred'=>'DH48', 'bidang'=>'KEJURUTERAAN MEKANIKAL', 'polikk'=>'KOLEJ KOMUNITI KEPALA BATAS', 'negeri'=>'KEDAH', 'tahun_lantikan'=>'2022', 'program'=>'TEKNOLOGI PEMBUATAN'],
            ['name'=>'TS. WAN MAJDAH BINTI TON MAMAT', 'email'=>'majdah@psa.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'811009115330', 'telefon'=>'0199541981', 'gred'=>'DH48', 'bidang'=>'KEJURUTERAAN MEKANIKAL', 'polikk'=>'POLITEKNIK SULTAN SALAHUDDIN ABDUL AZIZ SHAH ', 'negeri'=>'SELANGOR', 'tahun_lantikan'=>'2022', 'program'=>'KEJURUTERAAN MEKANIKAL'],
            ['name'=>'TS. ZETY SHAKILA BINTI MOHD YUSOF', 'email'=>'zetyshakila@pmjb.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'820928016426', 'telefon'=>'0127990765', 'gred'=>'DH48', 'bidang'=>'PENGURUSAN & PERDAGANGAN', 'polikk'=>'POLITEKNIK METRO JOHOR BHARU ', 'negeri'=>'JOHOR', 'tahun_lantikan'=>'2022', 'program'=>'DLS, DIB, DEN, DPM '],
            ['name'=>'UMI NORSALWA BINTI TUKIMAN', 'email'=>'norsalwa@kkrembau.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'811225015748', 'telefon'=>'0197672871', 'gred'=>'DH34', 'bidang'=>'REKA BENTUK & KREATIF', 'polikk'=>'KOLEJ KOMUNITI REMBAU', 'negeri'=>'NEGERI SEMBILAN', 'tahun_lantikan'=>'2022', 'program'=>'FESYEN & PAKAIAN'],
            ['name'=>'UMMU HANI BINTI YUSOF', 'email'=>'hani@kkselayang.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'820728015058', 'telefon'=>'Belum kemaskini', 'gred'=>'DH48', 'bidang'=>'REKA BENTUK & KREATIF', 'polikk'=>'KOLEJ KOMUNITI SELAYANG', 'negeri'=>'SELANGOR', 'tahun_lantikan'=>'2022', 'program'=>'GAMES ART'],
            ['name'=>'VIRANEE INTACHAT', 'email'=>'viranee@polimas.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH48', 'bidang'=>'KEJURUTERAAN ELEKTRIK', 'polikk'=>'POLITEKNIK SULTAN ABDUL HALIM MUADZAM SHAH ', 'negeri'=>'KEDAH', 'tahun_lantikan'=>'2022', 'program'=>'KEJURUTERAAN ELEKTRIK'],
            ['name'=>'WAN NORSARIZA BINTI WAN HUSIN', 'email'=>'norsariza@ptsb.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'Belum kemaskini', 'telefon'=>'Belum kemaskini', 'gred'=>'DH48', 'bidang'=>'PENGAJIAN UMUM', 'polikk'=>'POLITEKNIK TUANKU SULTANAH BAHIYAH ', 'negeri'=>'KEDAH', 'tahun_lantikan'=>'2022', 'program'=>'DKM'],
            ['name'=>'ZAIDAH BINTI MUSTAFA', 'email'=>'zaidah.mustafa@kkampang.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'750701145628', 'telefon'=>'0139286775', 'gred'=>'DH44', 'bidang'=>'KEJURUTERAAN ELEKTRIK', 'polikk'=>'KOLEJ KOMUNITI AMPANG', 'negeri'=>'SELANGOR', 'tahun_lantikan'=>'2022', 'program'=>'MOBILE TECH., TELECOMMUNICATION TECH.'],
            ['name'=>'ZAKIAH BINTI MD SAAD', 'email'=>'szakiah@polimas.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'730107075382', 'telefon'=>'0162282346', 'gred'=>'DH48', 'bidang'=>'KEJURUTERAAN ELEKTRIK', 'polikk'=>'POLITEKNIK SULTAN ABDUL HALIM MUADZAM SHAH', 'negeri'=>'KEDAH', 'tahun_lantikan'=>'2022', 'program'=>'KEJ. ELEKTRIK DAN ELEKTRONIK'],
            ['name'=>'ZARINA BINTI SAMIN', 'email'=>'zarina@kklej.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'820928016426', 'telefon'=>'0127990765', 'gred'=>'DH48', 'bidang'=>'PENGAJIAN UMUM', 'polikk'=>'KOLEJ KOMUNITI LEDANG', 'negeri'=>'JOHOR', 'tahun_lantikan'=>'2022', 'program'=>'PENDIDIKAN MORAL'],
            ['name'=>'ZULIANA BINTI ZULKIFLEE CHANDRA', 'email'=>'zuliana@kkklang.edu.my', 'password'=>bcrypt($defaultpwd), 'role'=>2, 'no_kp'=>'801016015996', 'telefon'=>'0166268806', 'gred'=>'DH44', 'bidang'=>'PERKOMPUTERAN', 'polikk'=>'KOLEJ KOMUNITI KLANG', 'negeri'=>'SELANGOR', 'tahun_lantikan'=>'2022', 'program'=>'KOMPUTER DAN RANGKAIAN'],
        ];
        
        User::insert($createMultipleUsers);
    }
}
