<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;

class PripSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $defaultpwd = '12345678';
        $createMultipleUsers = [
            ['name' => 'SALHANA BINTI SAHIDIN@SALEHUDIN', 'email' => 'salhana@psa.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '760228016116', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH52', 'bidang' => 'KEJURUTERAAN MEKANIKAL', 'program' => 'KEJURUTERAAN MEKANIKAL', 'polikk' => 'POLITEKNIK SULTAN SALAHUDDIN ABDUL AZIZ SHAH', 'negeri' => 'SELANGOR', 'emel_google' => 'salhana28276@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'DR. DULINA BINTI THOLIBON', 'email' => 'dulina@ptsn.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '810826065738', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH52', 'bidang' => 'KEJURUTERAAN MEKANIKAL', 'program' => 'KEJURUTERAAN MEKANIKAL', 'polikk' => 'POLITEKNIK TUN SYED NASIR SYED ISMAIL', 'negeri' => 'JOHOR', 'emel_google' => 'dulinatholibon@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'SHAIPUL ANUAR BIN MOHAMED ZAINUDIN', 'email' => 'shaipul@psas.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '730701115201', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH52', 'bidang' => 'KEJURUTERAAN MEKANIKAL', 'program' => 'KEJURUTERAAN MEKANIKAL', 'polikk' => 'POLITEKNIK SULTAN AZLAN SHAH', 'negeri' => 'PERAK', 'emel_google' => 'shaipulanuar73@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'NASRUL HAKIME BIN HASSAN', 'email' => 'nasrul@kkss.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '760829086355', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH40', 'bidang' => 'KEJURUTERAAN MEKANIKAL', 'program' => 'AUTOMOTIF (SERVIS KENDERAAN RINGAN)', 'polikk' => 'KOLEJ KOMUNITI SUNGAI SIPUT', 'negeri' => 'PERAK', 'emel_google' => 'nasrulhakime29876@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'JUMRIANI BINTI NONGKANG', 'email' => 'jumriani@polikk.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '780216125452', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH52', 'bidang' => 'KEJURUTERAAN ELEKTRIK', 'program' => 'KEJURUTERAAN ELEKTRIK', 'polikk' => 'POLITEKNIK KOTA KINABALU SABAH', 'negeri' => 'SABAH', 'emel_google' => 'jumriani1788@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'NOR \'AZIAH HJ ABDULLAH', 'email' => 'noraziah@pkb.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '630904035334', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH52', 'bidang' => 'KEJURUTERAAN ELEKTRIK', 'program' => 'KEJURUTERAAN ELEKTRIK', 'polikk' => 'POLITEKNIK KOTA BHARU', 'negeri' => 'KELANTAN', 'emel_google' => 'noraziah6394@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'MD EMRAN BIN SAIDI', 'email' => 'emran.kkbbm@celt.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '690129015707', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH48', 'bidang' => 'KEJURUTERAAN ELEKTRIK', 'program' => 'TEKNOLOGI ELEKTRIK', 'polikk' => 'KOLEJ KOMUNITI BUKIT BERUANG', 'negeri' => 'MELAKA', 'emel_google' => 'mdemransaidi@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'KHAIRULFADILAH BINTI MOHAMAD SAZALI', 'email' => 'kfadilah@poliku.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '811226135602', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH44', 'bidang' => 'KEJURUTERAAN ELEKTRIK', 'program' => 'KEJURUTERAAN ELEKTRIK', 'polikk' => 'POLITEKNIK KUCHING SARAWAK', 'negeri' => 'SARAWAK', 'emel_google' => 'dilotpun@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'NOORFOZILA BINTI BAHARI', 'email' => 'noorfozila@polisas.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '660904075376', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH54', 'bidang' => 'KEJURUTERAAN ELEKTRIK', 'program' => 'KEJURUTERAAN ELEKTRIK', 'polikk' => 'POLITEKNIK SULTAN HAJI AHMAD SHAH', 'negeri' => 'PAHANG', 'emel_google' => 'noorfozilabahari@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'FAIZAH BINTI AMIR', 'email' => 'faizah@polisas.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '660425035860', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH52', 'bidang' => 'KEJURUTERAAN ELEKTRIK', 'program' => 'KEJURUTERAAN ELEKTRIK', 'polikk' => 'POLITEKNIK SULTAN HAJI AHMAD SHAH', 'negeri' => 'PAHANG', 'emel_google' => 'ghaffa66@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'SULIE AK SLAT', 'email' => 'sulie@polikk.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '781108125118', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH52', 'bidang' => 'KEJURUTERAAN AWAM & ALAM BINA', 'program' => 'KEJURUTERAAN AWAM', 'polikk' => 'POLITEKNIK KOTA KINABALU SABAH', 'negeri' => 'SABAH', 'emel_google' => 'sulie6764@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'ZURAIDAH BINTI HASHIM', 'email' => 'zuraidahhashim@staff.polisas.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '760225055208', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH52', 'bidang' => 'KEJURUTERAAN AWAM & ALAM BINA', 'program' => 'KEJURUTERAAN AWAM', 'polikk' => 'POLITEKNIK SULTAN HAJI AHMAD SHAH', 'negeri' => 'PAHANG', 'emel_google' => 'ainaqilahsudean@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'ZARINAH BINTI ZAINI', 'email' => 'zzarinah@psa.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '700719105944', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH52', 'bidang' => 'KEJURUTERAAN AWAM & ALAM BINA', 'program' => 'KEJURUTERAAN AWAM', 'polikk' => 'POLITEKNIK SULTAN SALAHUDDIN ABDUL AZIZ SHAH', 'negeri' => 'SELANGOR', 'emel_google' => 'zzarinahkjka@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'NOR HAYATI BINTI AB. RAHIM', 'email' => 'hayati@psmza.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '760721115206', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH48', 'bidang' => 'KEJURUTERAAN AWAM & ALAM BINA', 'program' => 'KEJURUTERAAN AWAM', 'polikk' => 'POLITEKNIK SULTAN MIZAN ZAINAL ABIDIN', 'negeri' => 'TERENGGANU', 'emel_google' => 'norhayatiabrahim76@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'ROHAZA BINTI MAJID', 'email' => 'rohaza@psa.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '700701106826', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH48', 'bidang' => 'KEJURUTERAAN AWAM & ALAM BINA', 'program' => 'KEJURUTERAAN AWAM', 'polikk' => 'POLITEKNIK SULTAN SALAHUDDIN ABDUL AZIZ SHAH', 'negeri' => 'SELANGOR', 'emel_google' => 'smrohaza@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'FATIMAHWATI BT ABDUL HAMID', 'email' => 'fatimahwati@polinilai.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '660322075106', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH52', 'bidang' => 'KEJURUTERAAN AWAM & ALAM BINA', 'program' => 'SENIBINA LANDSKAP', 'polikk' => 'POLITEKNIK NILAI', 'negeri' => 'NEGERI SEMBILAN', 'emel_google' => 'wati220314@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'AZHAR BIN YAAKUB', 'email' => 'azhar@kkmasjidtanah.onmicrosoft.com', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '730906035539', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH52', 'bidang' => 'KEJURUTERAAN AWAM & ALAM BINA', 'program' => 'SENIBINA LANDSKAP', 'polikk' => 'KOLEJ KOMUNITI MASJID TANAH', 'negeri' => 'MELAKA', 'emel_google' => 'awesender@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'MOHAMAD IMRAN BIN HASSAN', 'email' => 'imran@kkmasjidtanah.onmicrosoft.com', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '791114035417', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH48', 'bidang' => 'KEJURUTERAAN AWAM & ALAM BINA', 'program' => 'SENIBINA LANDSKAP', 'polikk' => 'KOLEJ KOMUNITI MASJID TANAH', 'negeri' => 'MELAKA', 'emel_google' => 'imran.hjhassan@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'MOHD AZRAN BIN MOHD SALLEH', 'email' => 'azran@kkselandar.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '790225025479', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH48', 'bidang' => 'PERKOMPUTERAN', 'program' => 'SISTEM KOMPUTER DAN RANGKAIAN', 'polikk' => 'KOLEJ KOMUNITI SELANDAR', 'negeri' => 'MELAKA', 'emel_google' => 'mrazransalleh@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'HAMIDAH BINTI MOHAMED SHAH', 'email' => 'hamidah@kkmasjidtanah.onmicrosoft.com', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '771003055150', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH48', 'bidang' => 'PERKOMPUTERAN', 'program' => 'TEKNOLOGI MAKLUMAT', 'polikk' => 'KOLEJ KOMUNITI MASJID TANAH', 'negeri' => 'MELAKA', 'emel_google' => 'middizzy1@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'NORSHAHADAH BINTI ABD RAHMAN', 'email' => 'norshahadah@pss.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '780827105960', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH44', 'bidang' => 'PERKOMPUTERAN', 'program' => 'TEKNOLOGI MAKLUMAT', 'polikk' => 'POLITEKNIK SANDAKAN SABAH', 'negeri' => 'SABAH', 'emel_google' => 'shahadahpss@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'SUDIMAN BIN SUHAILI', 'email' => 'sudiman@pmu.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '800511135333', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH48', 'bidang' => 'PERKOMPUTERAN', 'program' => 'TEKNOLOGI MAKLUMAT', 'polikk' => 'POLITEKNIK MUKAH', 'negeri' => 'SARAWAK', 'emel_google' => 'sudiman1980@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'ULAIMI YAHYA', 'email' => 'ulaimi@pjk.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '690706035047', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH52', 'bidang' => 'PENGURUSAN & PERDAGANGAN', 'program' => 'PERDAGANGAN', 'polikk' => 'POLITEKNIK JELI', 'negeri' => 'KELANTAN', 'emel_google' => 'ulaimi@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'SALEHAN BIN MARSIM', 'email' => 'salehan@psas.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '670315015163', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH52', 'bidang' => 'PENGURUSAN & PERDAGANGAN', 'program' => 'PERDAGANGAN', 'polikk' => 'POLITEKNIK SULTAN AZLAN SHAH', 'negeri' => 'PERAK', 'emel_google' => 'salehanmarsim@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'ATI ARINI BT SALIM', 'email' => 'atiarini@polipd.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '710129015630', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH52', 'bidang' => 'PENGURUSAN & PERDAGANGAN', 'program' => 'PERAKAUNAN', 'polikk' => 'POLITEKNIK PORT DICKSON', 'negeri' => 'NEGERI SEMBILAN', 'emel_google' => 'atiarinisalim71@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'YUFIZA BINTI MOHD YUSOF', 'email' => 'yufiza@puo.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '611105055300', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'BERSARA', 'bidang' => 'PENGURUSAN & PERDAGANGAN', 'program' => 'PERAKAUNAN', 'polikk' => 'TELAH BERSARA', 'negeri' => 'PERAK', 'emel_google' => 'fairladyi61@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'HASNIDA BINTI ISMAIL', 'email' => 'hasnida_ismail@pms.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '710227055468', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH52', 'bidang' => 'PENGURUSAN & PERDAGANGAN', 'program' => 'STATISTIK / BUSINESS', 'polikk' => 'POLITEKNIK MUADZAM SHAH', 'negeri' => 'PAHANG', 'emel_google' => 'ismail.hasnida@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'SUZILA BINTI ABDUL LATIFF', 'email' => 'suzila@lecturer.kklej.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '740714115496', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH44', 'bidang' => 'PENGURUSAN & PERDAGANGAN', 'program' => 'ETIKA PERNIAGAAN', 'polikk' => 'KOLEJ KOMUNITI LEDANG', 'negeri' => 'JOHOR', 'emel_google' => 'suzila714@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'AHMAD RASA\'ARIM BIN RAZZALI', 'email' => 'ahmad.rasaarim@pmku.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '640626065005', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH52', 'bidang' => 'HOSPITALITI & PELANCONGAN', 'program' => 'HOSPITALITI (PERKHIDMATAN MAKANAN)', 'polikk' => 'POLITEKNIK METrO KUANTAN', 'negeri' => 'PAHANG', 'emel_google' => 'rasaarimmetro@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'ZAKINA IZIENTY BINTI ZAINAL', 'email' => 'zakina@kkss.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '770522086026', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH48', 'bidang' => 'HOSPITALITI & PELANCONGAN', 'program' => 'PENGEMBARAAN PELANCONGAN', 'polikk' => 'CUTI BELAJAR', 'negeri' => 'PERAK', 'emel_google' => 'izientyz@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'KHAIRUL ASHIKHIN BT ABDULLAH SUHAMI', 'email' => 'ashikhin@kkchenderoh.onmicrosoft.com', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '800810025978', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH52', 'bidang' => 'PENGAJIAN PERKHIDMATAN', 'program' => 'KULINARI', 'polikk' => 'KOLEJ KOMUNITI CHENDEROH', 'negeri' => 'PERAK', 'emel_google' => 'ashikhinsuhami@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'ZAFEERA BINTI ZULKEFLI', 'email' => 'zafeera.zulkefli.kk@1govuc.gov.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '811118105692', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH42', 'bidang' => 'PENGAJIAN PERKHIDMATAN', 'program' => 'KULINARI', 'polikk' => 'KOLEJ KOMUNITI KOTA MELAKA', 'negeri' => 'MELAKA', 'emel_google' => 'zafeerazulkefli@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'INTANKU SALWA BT SHAMSUDDIN', 'email' => 'intankusalwa@staff.pmm.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '691111015930', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH48', 'bidang' => 'PENGAJIAN UMUM', 'program' => 'PENDIDIKAN MATEMATIK', 'polikk' => 'POLITEKNIK MERLIMAU MELAKA', 'negeri' => 'MELAKA', 'emel_google' => 'intankusalwa11@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'LIM BOON PING', 'email' => 'limbp@pbu.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '740712035265', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH48', 'bidang' => 'PENGAJIAN UMUM', 'program' => 'MATEMATIK / IT', 'polikk' => 'POLITEKNIK BALIK PULAU', 'negeri' => 'PULAU PINANG', 'emel_google' => 'lim.pbu@celt.edu.my', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'KHAIRUL ANUAR BIN KAMAR', 'email' => 'khairul_anuar@kkpbe.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '730701115201', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH52', 'bidang' => 'PENGAJIAN UMUM', 'program' => 'PENDIDIKAN ISLAM', 'polikk' => 'KOLEJ KOMUNITI PAYA BESAR', 'negeri' => 'PAHANG', 'emel_google' => 'khairulanuar.abi@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2021', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'AINA FATHIAH BINTI ZUHAIDI', 'email' => 'a.fathiah@ptsn.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '870202115316', 'telefon' => '0133665645', 'gred' => 'DH48', 'bidang' => 'TEKNOLOGI PERTANIAN', 'program' => 'TEKNOLOGI KIMIA (LEMAK & MINYAK)', 'polikk' => 'POLITEKNIK TUN SYED NASIR SYED ISMAIL', 'negeri' => 'JOHOR', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'AINUL AZNIZA BINTI AHMAD ZAINI', 'email' => 'ainul@pmm.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '760124025042', 'telefon' => '0192649842', 'gred' => 'DH48', 'bidang' => 'KEJURUTERAAN MEKANIKAL', 'program' => 'KEJURUTERAAN MEKATRONIK', 'polikk' => 'POLITEKNIK MERLIMAU MELAKA ', 'negeri' => 'MELAKA', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'AINUL HUSNA BINTI ABDUL HALIM', 'email' => 'ainul@kkbaganserai.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '881214025434', 'telefon' => '0174669836', 'gred' => 'DH44', 'bidang' => 'TEKNOLOGI PERTANIAN', 'program' => 'PEMPROSESAN DAN KAWALAN MUTU MAKANAN', 'polikk' => 'KOLEJ KOMUNITI BAGAN SERAI', 'negeri' => 'PULAU PINANG', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'AZLILAWATI BINTI ABU BAKAR', 'email' => 'azlilawati@pmm.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '720711015598', 'telefon' => '0196697051', 'gred' => 'DH48', 'bidang' => 'KEJURUTERAAN ELEKTRIK', 'program' => 'KEJURUTERAAN ELEKTRONIK (KOMUNIKASI)', 'polikk' => 'POLITEKNIK MERLIMAU MELAKA ', 'negeri' => 'MELAKA', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'AZLINA BINTI ABDUL AZIZ', 'email' => 'azlina@pmu.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '810514085764', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH48', 'bidang' => 'KEJURUTERAAN ELEKTRIK', 'program' => 'KEJURUTERAAN ELEKTRONIK (KOMUNIKASI)', 'polikk' => 'POLITEKNIK MUKAH SARAWAK ', 'negeri' => 'SARAWAK', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'CHE AZLINA BINTI CHE NOROHOSENI', 'email' => 'cheazlina@polipd.edy.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '810711095056', 'telefon' => '012-4632620', 'gred' => 'DH48', 'bidang' => 'KEJURUTERAAN MEKANIKAL', 'program' => 'KEJURUTERAAN MEKANIKAL', 'polikk' => 'POLITEKNIK PORT DICKSON ', 'negeri' => 'NEGERI SEMBILAN', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'CHE KU FARHANA BINTI CHE KU ALAM', 'email' => 'farhana@kkktu.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '820204115218', 'telefon' => '0125238489', 'gred' => 'DH44', 'bidang' => 'KEJURUTERAAN ELEKTRIK', 'program' => 'TEKNOLOGI ELEKTRIK', 'polikk' => 'KOLEJ KOMUNITI KUALA TERENGGANU', 'negeri' => 'TERENGGANU', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'CR. DR. LING YING LEH', 'email' => 'jossted@poliku.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '740831135285', 'telefon' => '0163982588', 'gred' => 'DH52', 'bidang' => 'PENGAJIAN UMUM', 'program' => 'MATEMATIK, SAINS DAN KOMPUTER', 'polikk' => 'POLITEKNIK KUCHING SARAWAK ', 'negeri' => 'SARAWAK', 'emel_google' => 'lingyingleh@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'DR. MUHAMMAD NAZRI BIN ABDUL HALIM', 'email' => 'nazrifaiz@yahoo.com', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '770222016341', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH52', 'bidang' => 'PENGURUSAN & PERDAGANGAN', 'program' => 'DLS, DIB, DEN, DPM ', 'polikk' => 'POLITEKNIK METrO JOHOR BAHRU ', 'negeri' => 'JOHOR', 'emel_google' => 'nazrifaiz@yahoo.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'ENI BINTI AZNAN', 'email' => 'enikkbk16@gmail.com', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '801026025928', 'telefon' => '0126676476', 'gred' => 'DH44', 'bidang' => 'REKA BENTUK & KREATIF', 'program' => 'FESYEN & PAKAIAN', 'polikk' => 'KOLEJ KOMUNITI BUKIT MERTAJAM', 'negeri' => 'PULAU PINANG', 'emel_google' => 'enikkbk16@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'JULIA BINTI JAMALUDDIN', 'email' => 'julia@pkb.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '810122045368', 'telefon' => '0133387578', 'gred' => 'DH44', 'bidang' => 'KEJURUTERAAN MEKANIKAL', 'program' => 'AGRICULTURE ENGINEERING', 'polikk' => 'POLITEKNIK KOTA BHARU ', 'negeri' => 'KELANTAN', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'JULIANA BINTI MD JUSOH', 'email' => 'juliana@pkb.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '790409015224', 'telefon' => '0132373792', 'gred' => 'DH48', 'bidang' => 'KEJURUTERAAN ELEKTRIK', 'program' => 'KEJURUTERAAN ELEKTRIK', 'polikk' => 'POLITEKNIK KOTA BHARU ', 'negeri' => 'KELANTAN', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'KHIRUN BIN MD SHAH', 'email' => 'khirun@psis.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '790730075733', 'telefon' => '0193348005', 'gred' => 'DH48', 'bidang' => 'HOSPITALITI & PELANCONGAN', 'program' => 'PENGURUSAN PELANCONGAN', 'polikk' => 'POLITEKNIK SULTAN IDRIS SHAH ', 'negeri' => 'SELANGOR', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'LAILA BINTI MUSA', 'email' => 'laila@ptss.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '761120025330', 'telefon' => '0192586555', 'gred' => 'DH52', 'bidang' => 'PENGURUSAN & PERDAGANGAN', 'program' => 'AKAUNTANSI', 'polikk' => 'POLITEKNIK TUANKU SYED SIRAJUDDIN ', 'negeri' => 'PERLIS', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'LATENAZURAINI BINTI SAARI', 'email' => 'latenazuraini@polipd.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '770331086250', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH48', 'bidang' => 'KEJURUTERAAN ELEKTRIK', 'program' => 'KEJURUTERAAN ELEKTRIK', 'polikk' => 'POLITEKNIK PORT DICKSON', 'negeri' => 'NEGERI SEMBILAN', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'LENNY LAI MEI LAN', 'email' => 'lennylml@kkmas.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '820830135590', 'telefon' => '0177557163', 'gred' => 'DH48', 'bidang' => 'PERKOMPUTERAN', 'program' => 'TEKNOLOGI MAKLUMAT', 'polikk' => 'KOLEJ KOMUNITI MAS GADING', 'negeri' => 'SARAWAK', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'TS. MAHALETCHUMY A/P KRISHNAMOORTHY', 'email' => 'maha@kkrembau.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '860710565808', 'telefon' => '0102059448', 'gred' => 'DH44', 'bidang' => 'TEKNOLOGI PERTANIAN', 'program' => 'AGROTEKNOLOGI', 'polikk' => 'KOLEJ KOMUNITI REMBAU', 'negeri' => 'NEGERI SEMBILAN', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'MANISAH BINTI ABD HAMID', 'email' => 'manisah@mail.cckk.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '831128086120', 'telefon' => '0124174001', 'gred' => 'DH44', 'bidang' => 'HOSPITALITI & PELANCONGAN', 'program' => 'SPT , DPT', 'polikk' => 'KOLEJ KOMUNITI KUALA KANGSAR', 'negeri' => 'PERAK', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'MARZITA BINTI MUHAMAD TAZI', 'email' => 'marzita.tazi@polikk.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '771117146042', 'telefon' => '0123195642', 'gred' => 'DH52', 'bidang' => 'KEJURUTERAAN ELEKTRIK', 'program' => 'KEJURUTERAAN ELEKTRIK', 'polikk' => 'BAHAGIAN KURIKULUM, JPPKK', 'negeri' => 'WILAYAH PERSEKUTUAN PUTRAJAYA', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'MOHAMAD ZULHILMY BIN MOHAMAD YUSOP', 'email' => 'zulhilmy@politawau.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '760210145067', 'telefon' => '0127036308', 'gred' => 'DH48', 'bidang' => 'HOSPITALITI & PELANCONGAN', 'program' => 'PENGURUSAN PELANCONGAN', 'polikk' => 'POLITEKNIK TAWAU ', 'negeri' => 'SABAH', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'MOHAMMAD AZMIN BIN ZAINAL', 'email' => 'azmin@polibanting.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '870206385049', 'telefon' => '0199199085', 'gred' => 'DH44', 'bidang' => 'KEJURUTERAAN MEKANIKAL', 'program' => 'KEJURUTERAAN PENYENGGARAAN PESAWAT', 'polikk' => 'POLITEKNIK BANTING ', 'negeri' => 'SELANGOR', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'MOHAMMAD HAIRY BIN KHARAUDDIN', 'email' => 'mhairydin5857@gmail.com', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '820401015857', 'telefon' => '0133374812', 'gred' => 'DH48', 'bidang' => 'KEJURUTERAAN ELEKTRIK', 'program' => 'RAIL SIGNALLING & COMMUNICATION TECH.', 'polikk' => 'KOLEJ KOMUNITI MASJID TANAH', 'negeri' => 'MELAKA', 'emel_google' => 'mhairydin5857@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'MOHD AZIAN BIN HUSIN @ CHE HAMAT', 'email' => 'azian@kkpmas.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '800416035465', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH52', 'bidang' => 'PENGURUSAN & PERDAGANGAN', 'program' => 'PERKHIDMATAN LOGISTIK', 'polikk' => 'KOLEJ KOMUNITI CAW. RANTAU PANJANG', 'negeri' => 'KELANTAN', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'TS. MOHD NAIM BIN AWANG', 'email' => 'mnaim@puo.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '820606025127', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH52', 'bidang' => 'KEJURUTERAAN MEKANIKAL', 'program' => 'SENIBINA KAPAL ', 'polikk' => 'POLITEKNIK BAGAN DATUK ', 'negeri' => 'PERAK', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'MOHD SHAHRIR BIN AHMAD ZAINI', 'email' => 'mohdshahrir@pmbs.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '760621085185', 'telefon' => '0197727323', 'gred' => 'DH48', 'bidang' => 'HOSPITALITI & PELANCONGAN', 'program' => 'PENGURUSAN PELANCONGAN (DUP)', 'polikk' => 'POLITEKNIK METRO BETONG ', 'negeri' => 'SARAWAK', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'MOHD ZAMRI BIN JAMALUDIN', 'email' => 'zamri_jamaludin@psis.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '790816085115', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH44', 'bidang' => 'KEJURUTERAAN AWAM & ALAM BINA', 'program' => 'KEJURUTERAAN ALAM SEKITAR', 'polikk' => 'POLITEKNIK SULTAN IDRIS SHAH ', 'negeri' => 'SELANGOR', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'MUHAMMAD ISWAN BIN MOHAMAD AYOB', 'email' => 'iswan@polibanting.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '820422016197', 'telefon' => '0127343802', 'gred' => 'DH48', 'bidang' => 'KEJURUTERAAN MEKANIKAL', 'program' => 'PENYENGGARAAN PESAWAT/DAM', 'polikk' => 'POLITEKNIK BANTING SELANGOR ', 'negeri' => 'SELANGOR', 'emel_google' => 'iswan_pbs@yahoo.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'MUHD FADHLULLAH BIN RASHID', 'email' => 'muhd_fadhlullah@psmza.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '821115115149', 'telefon' => '0122844475', 'gred' => 'DH52', 'bidang' => 'KEJURUTERAAN AWAM & ALAM BINA', 'program' => 'KEJURUTERAAN AWAM', 'polikk' => 'POLITEKNIK SULTAN MIZAN ZAINAL ABIDIN ', 'negeri' => 'TERENGGANU', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'NGATINAH BINTI JASWADI', 'email' => 'ngatinah@pmm.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '760919017046', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH44', 'bidang' => 'PENGAJIAN UMUM', 'program' => 'SAINS DAN MATEMATIK', 'polikk' => 'POLITEKNIK MERLIMAU MELAKA ', 'negeri' => 'MELAKA', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'NOR ASMA BINTI MAMAT', 'email' => 'nor.asma@pkb.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '821020035402', 'telefon' => '0199162266', 'gred' => 'DH48', 'bidang' => 'KEJURUTERAAN AWAM & ALAM BINA', 'program' => 'UKUR BAHAN', 'polikk' => 'POLITEKNIK KOTA BHARU ', 'negeri' => 'KELANTAN', 'emel_google' => 'nor.asma@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'NOR AZIMAH BINTI MUSTAFAR', 'email' => 'norazimah.mus@puo.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '820731085516', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH44', 'bidang' => 'PENGAJIAN UMUM', 'program' => 'MATEMATIK, SAINS DAN KOMPUTER', 'polikk' => 'POLITEKNIK UNGKU OMAR', 'negeri' => 'PERAK', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'NORAWATI BINTI MASRO', 'email' => 'masronorawati@gmail.com', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '750113015296', 'telefon' => '0192339336', 'gred' => 'DH48', 'bidang' => 'KEJURUTERAAN ELEKTRIK', 'program' => 'TEKNOLOGI ELEKTRIK', 'polikk' => 'KOLEJ KOMUNITI SABAK BERNAM', 'negeri' => 'SELANGOR', 'emel_google' => 'masronorawati@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'NORIZZATI BINTI ABD LATIF', 'email' => 'norizzati@pms.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '820528145552', 'telefon' => '0123644611', 'gred' => 'DH48', 'bidang' => 'REKA BENTUK & KREATIF', 'program' => 'TEKNOLOGI MEDIA CETAK', 'polikk' => 'POLITEKNIK MUADZAM SHAH ', 'negeri' => 'PAHANG', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'NORLEZA BINTI LEHAT', 'email' => 'norleza@pms.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '751023015748', 'telefon' => '0126077458', 'gred' => 'DH48', 'bidang' => 'PENGURUSAN & PERDAGANGAN', 'program' => 'PENGAJIAN PERNIAGAAN, AKAUNTANSI', 'polikk' => 'POLITEKNIK MUADZAM SHAH ', 'negeri' => 'PAHANG', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'RAFIZAH BINTI SHAHARUDDIN', 'email' => 'rafizah@pbu.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '770511087306', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH48', 'bidang' => 'PERKOMPUTERAN', 'program' => 'TEKNOLOGI MAKLUMAT (TEKNOLOGI DIGITAL)', 'polikk' => 'POLITEKNIK BALIK PULAU ', 'negeri' => 'PULAU PINANG', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'RAZZATUL IZA ZURITA BINTI RASALLI', 'email' => 'iza@lecturer.kklej.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '810225145564', 'telefon' => '0176057054', 'gred' => 'DH48', 'bidang' => 'PENGAJIAN UMUM', 'program' => 'SAINS', 'polikk' => 'KOLEJ KOMUNITI LEDANG', 'negeri' => 'JOHOR', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'SAPTUAH@SAPTUYAH BT.MARJIRI', 'email' => 'saptuyah@pmbs.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '650925135244', 'telefon' => '0194100019', 'gred' => 'DH48', 'bidang' => 'PENGURUSAN & PERDAGANGAN', 'program' => 'PERDAGANGAN', 'polikk' => 'POLITEKNIK METRO BETONG SARAWAK', 'negeri' => 'SARAWAK', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'SARAH NARIMAH NOORAZYZE BINTI ZAINAL RAMLAN', 'email' => 'sarah@polinilai.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '810426016304', 'telefon' => '0168530506', 'gred' => 'DH48', 'bidang' => 'KEJURUTERAAN MEKANIKAL', 'program' => 'KEJURUTERAAN MEKANIKAL', 'polikk' => 'POLITEKNIK NILAI ', 'negeri' => 'NEGERI SEMBILAN', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'SITI FADZLINA BINTI MOHAMAD ASRI', 'email' => 'ctfadzlina@psa.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '770105145072', 'telefon' => '0193329569', 'gred' => 'DH48', 'bidang' => 'PENGAJIAN UMUM', 'program' => 'MATEMATIK, SAINS DAN KOMPUTER', 'polikk' => 'POLITEKNIK SULTAN SALAHUDDIN ABDUL AZIZ SHAH ', 'negeri' => 'SELANGOR', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'SITI NORSHAFINAZ BINTI MOHD NOH', 'email' => 'nshafinaz@puo.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '810309105244', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH48', 'bidang' => 'PENGAJIAN UMUM', 'program' => 'MATEMATIK, SAINS DAN KOMPUTER', 'polikk' => 'POLITEKNIK UNGKU OMAR ', 'negeri' => 'PERAK', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'SYAKIRAH BINTI MANSOR', 'email' => 'syakirah@tvet.pmj.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '820404016054', 'telefon' => '0197508482', 'gred' => 'DH48', 'bidang' => 'PERKOMPUTERAN', 'program' => 'TEKNOLOGI MAKLUMAT (TEKNOLOGI DIGITAL)', 'polikk' => 'POLITEKNIK MERSING ', 'negeri' => 'JOHOR', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'TS. BABBY FRESKAYANI@ IZYANI BINTI KALIWON', 'email' => 'izyani@polikk.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '820116715002', 'telefon' => '0178961511', 'gred' => 'DH52', 'bidang' => 'KEJURUTERAAN AWAM & ALAM BINA', 'program' => 'KEJURUTERAAN AWAM', 'polikk' => 'POLITEKNIK KOTA KINABALU', 'negeri' => 'SABAH', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'TS. DR. SHARIFAH NADIYAH BINTI RAZALI', 'email' => 'sharifahnadiyah@staf.kkselandar.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '810510045378', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH48', 'bidang' => 'PERKOMPUTERAN', 'program' => 'KOMPUTER DAN RANGKAIAN', 'polikk' => 'KOLEJ KOMUNITI SELANDAR', 'negeri' => 'MELAKA', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'TS. JALIFA BINTI RIDZUAN', 'email' => 'jalifa@live.com', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '840801126124', 'telefon' => '0173767267', 'gred' => 'DH48', 'bidang' => 'TEKNOLOGI PERTANIAN', 'program' => 'PEMPROSESAN DAN KAWALAN MUTU MAKANAN', 'polikk' => 'KOLEJ KOMUNITI JELEBU', 'negeri' => 'NEGERI SEMBILAN', 'emel_google' => 'jalifa@live.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'TS. KASLIA BINTI KASIRAN', 'email' => 'kaslia@kkkla.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '790409015224', 'telefon' => '0132373792', 'gred' => 'DH48', 'bidang' => 'KEJURUTERAAN ELEKTRIK', 'program' => 'TEKNOLOGI ELEKTRIK', 'polikk' => 'KOLEJ KOMUNITI KUALA LANGAT', 'negeri' => 'SELANGOR', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'TS. KASWATI BINTI SALLEH', 'email' => 'kaswatisalleh@gmail.com', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '791119035774', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH48', 'bidang' => 'PERKOMPUTERAN', 'program' => 'TEKNOLOGI MAKLUMAT', 'polikk' => 'KOLEJ KOMUNITI KUALA LANGAT', 'negeri' => 'SELANGOR', 'emel_google' => 'kaswatisalleh@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'Ts. MOHANADHAS KANAGARAJ', 'email' => 'stbmohan@gmail.com', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '760315025811', 'telefon' => '0194566184', 'gred' => 'DH48', 'bidang' => 'KEJURUTERAAN MEKANIKAL', 'program' => 'TEKNOLOGI PEMBUATAN', 'polikk' => 'KOLEJ KOMUNITI KEPALA BATAS', 'negeri' => 'KEDAH', 'emel_google' => 'stbmohan@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'TS. WAN MAJDAH BINTI TON MAMAT', 'email' => 'majdah@psa.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '811009115330', 'telefon' => '0199541981', 'gred' => 'DH48', 'bidang' => 'KEJURUTERAAN MEKANIKAL', 'program' => 'KEJURUTERAAN MEKANIKAL', 'polikk' => 'POLITEKNIK SULTAN SALAHUDDIN ABDUL AZIZ SHAH ', 'negeri' => 'SELANGOR', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'TS. ZETY SHAKILA BINTI MOHD YUSOF', 'email' => 'zetyshakila@pmjb.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '820928016426', 'telefon' => '0127990765', 'gred' => 'DH48', 'bidang' => 'PENGURUSAN & PERDAGANGAN', 'program' => 'DLS, DIB, DEN, DPM ', 'polikk' => 'POLITEKNIK METRO JOHOR BHARU ', 'negeri' => 'JOHOR', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'UMI NORSALWA BINTI TUKIMAN', 'email' => 'norsalwa@kkrembau.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '811225015748', 'telefon' => '0197672871', 'gred' => 'DH34', 'bidang' => 'REKA BENTUK & KREATIF', 'program' => 'FESYEN & PAKAIAN', 'polikk' => 'KOLEJ KOMUNITI REMBAU', 'negeri' => 'NEGERI SEMBILAN', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'UMMU HANI BINTI YUSOF', 'email' => 'hani@kkselayang.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '820728015058', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH48', 'bidang' => 'REKA BENTUK & KREATIF', 'program' => 'GAMES ART', 'polikk' => 'KOLEJ KOMUNITI SELAYANG', 'negeri' => 'SELANGOR', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'VIRANEE INTACHAT', 'email' => 'viranee@polimas.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '730914035600', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH48', 'bidang' => 'KEJURUTERAAN ELEKTRIK', 'program' => 'KEJURUTERAAN ELEKTRIK', 'polikk' => 'POLITEKNIK SULTAN ABDUL HALIM MUADZAM SHAH ', 'negeri' => 'KEDAH', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'WAN NORSARIZA BINTI WAN HUSIN', 'email' => 'norsariza@ptsb.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '750527065496', 'telefon' => 'BELUM DIKEMASKINI', 'gred' => 'DH48', 'bidang' => 'PENGAJIAN UMUM', 'program' => 'DKM', 'polikk' => 'POLITEKNIK TUANKU SULTANAH BAHIYAH ', 'negeri' => 'KEDAH', 'emel_google' => 'sariza5671@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'ZAIDAH BINTI MUSTAFA', 'email' => 'zaidah.mustafa@kkampang.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '750701145628', 'telefon' => '0139286775', 'gred' => 'DH44', 'bidang' => 'KEJURUTERAAN ELEKTRIK', 'program' => 'MOBILE TECH., TELECOMMUNICATION TECH.', 'polikk' => 'KOLEJ KOMUNITI AMPANG', 'negeri' => 'SELANGOR', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'ZAKIAH BINTI MD SAAD', 'email' => 'szakiah@polimas.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '730107075382', 'telefon' => '0162282346', 'gred' => 'DH48', 'bidang' => 'KEJURUTERAAN ELEKTRIK', 'program' => 'KEJ. ELEKTRIK DAN ELEKTRONIK', 'polikk' => 'POLITEKNIK SULTAN ABDUL HALIM MUADZAM SHAH', 'negeri' => 'KEDAH', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'ZARINA BINTI SAMIN', 'email' => 'zarina@kklej.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '820928016426', 'telefon' => '0127990765', 'gred' => 'DH48', 'bidang' => 'PENGAJIAN UMUM', 'program' => 'PENDIDIKAN MORAL', 'polikk' => 'KOLEJ KOMUNITI LEDANG', 'negeri' => 'JOHOR', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'ZULIANA BINTI ZULKIFLEE CHANDRA', 'email' => 'zuliana@kkklang.edu.my', 'password'=>bcrypt($defaultpwd), 'role' => '2', 'no_kp' => '801016015996', 'telefon' => '0166268806', 'gred' => 'DH44', 'bidang' => 'PERKOMPUTERAN', 'program' => 'KOMPUTER DAN RANGKAIAN', 'polikk' => 'KOLEJ KOMUNITI KLANG', 'negeri' => 'SELANGOR', 'emel_google' => '-', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2022', 'status' => '1', 'bil_aktiviti' => '0'],
            ['name' => 'MOHD IDHAM BIN ANUR', 'email' => 'idhamanur@gmail.com', 'password'=>bcrypt($defaultpwd), 'role' => '1', 'no_kp' => '801016015996', 'telefon' => '0166268806', 'gred' => 'DH44', 'bidang' => 'PERKOMPUTERAN', 'program' => 'KEJURUTERAAN PERISIAN', 'polikk' => 'MOHE', 'negeri' => 'SELANGOR', 'emel_google' => 'idhamanur@gmail.com', 'bulan_lantikan' => 'Disember', 'tahun_lantikan' => '2020', 'status' => '1', 'bil_aktiviti' => '0']
        ];
        
        User::insert($createMultipleUsers);
    }
}
